spring:
  application:
    name: user-center

  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis:
  basepackage: com.github.wxiaoqi.learning.uc.mapper
  xmlLocation: classpath:mapper/**/*.xml

server:
  port: 7771

#apollo的Spring Boot集成方式
apollo:
  bootstrap:
    enabled: true
    namespaces: application   # apollo namespace  配置多个namespace之间用逗号隔开

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  token-header: access-token
  pub-key:
    path: D:\workspace-idea\ag-parent\ag-uc\src\main\resources\jwt\pub.key

client:
  id: user-center
  secret: 123456
  token-header: client-token
  pub-key:
    path: D:\workspace-idea\ag-parent\ag-uc\src\main\resources\client\pub.key